raw-labs/snapi

- raw-compiler-rql2-truffle/src/main/scala/raw/compiler/rql2/truffle/Rql2TruffleCompiler.scala
- raw-compiler-rql2-truffle/src/main/scala/raw/compiler/rql2/truffle/TruffleEntryExtension.scala
- raw-compiler-rql2-truffle/src/main/scala/raw/compiler/rql2/truffle/builtin/TruffleBinaryPackage.scala
- raw-compiler-rql2-truffle/src/main/scala/raw/compiler/rql2/truffle/builtin/TruffleCsvPackage.scala
- raw-compiler-rql2-truffle/src/main/scala/raw/compiler/rql2/truffle/builtin/TruffleFunctionPackage.scala
- raw-compiler-rql2-truffle/src/main/scala/raw/compiler/rql2/truffle/builtin/TruffleJsonPackage.scala
- raw-compiler-rql2-truffle/src/main/scala/raw/compiler/rql2/truffle/builtin/TruffleStringPackage.scala
- raw-compiler-rql2-truffle/src/main/scala/raw/compiler/rql2/truffle/builtin/TruffleTimePackage.scala
- raw-compiler-rql2-truffle/src/main/scala/raw/compiler/rql2/truffle/builtin/TruffleTypePackage.scala
- raw-compiler-rql2-truffle/src/main/scala/raw/compiler/truffle/TruffleCompiler.scala
- raw-compiler-rql2-truffle/src/test/scala/raw/compiler/rql2/tests/extensions/TruffleExtensionsTest.scala
- raw-compiler-rql2-truffle/src/test/scala/raw/compiler/rql2/tests/output/TruffleOutputTest.scala
- raw-compiler-rql2/src/main/scala/raw/compiler/rql2/builtin/TimePackage.scala
- raw-compiler-rql2/src/main/scala/raw/compiler/rql2/builtin/TimestampPackage.scala
- raw-compiler-rql2/src/main/scala/raw/compiler/rql2/errors/ErrorsPrettyPrinter.scala
- raw-compiler-rql2/src/main/scala/raw/compiler/rql2/source/SourceCommentsPrettyPrinter.scala
- raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/output/BinaryOutputTest.scala
- raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/binary/BinaryBytesWriterNode.java
- raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/binary/BinaryWriterNode.java
- raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/binary/NullableBinaryWriterNode.java
- raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/binary/TryableBinaryWriterNode.java
- raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/runtime/exceptions/binary/BinaryWriterRawTruffleException.java
Two patches in that changeset:
* The "binary" output format + two new tests
* Compilation warnings fixes
> RD-9093: Implemented Truffle's "binary" output format

- project/Dependencies.scala
The current version presents a vuln issue (check JIRA for more details)
> RD-9186 upgrade snowflake-jdbc dep

- raw-compiler-rql2-truffle/src/main/scala/raw/compiler/rql2/truffle/builtin/TruffleS3Package.scala
- raw-compiler-rql2-truffle/src/test/scala/raw/compiler/rql2/tests/builtin/TruffleBuiltInTest.scala
- Implemented S3 package in Truffle
> RD-9177 Added S3 package to truffle

- .github/workflows/publish.yaml
stdout of github actions can be tricky sometimes
> fix: PR ChatOps /publish command

- project/Dependencies.scala
The current version presents a vuln issue (check JIRA for more details)
> RD-9187 upgrade sqlite-jdbc dep

- project/Dependencies.scala
The current version presents a vuln issue (check JIRA for more details)
> RD-9184 upgrade guava dep

- raw-creds-api/src/test/scala/raw/creds/OAuth2TestCreds.scala
Make use of the existing env variables for google api tests context
> chore: use env for google api tests

- raw-cli/src/main/scala/raw/cli/RawCli.scala
- raw-compiler-rql2-truffle/src/main/scala/raw/compiler/rql2/truffle/Rql2TruffleCompiler.scala
- raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/CompilerTestContext.scala
- raw-compiler/src/main/scala/raw/compiler/Errors.scala
- raw-compiler/src/main/scala/raw/compiler/Program.scala
Ensure Compiler throws CompilerException or children.
Change test infra and CLI to capture those instead.
> Fix exception handling for the Compiler API.

- raw-compiler-rql2-truffle/src/main/resources/META-INF/services/raw.compiler.rql2.EntryExtension
- raw-compiler-rql2-truffle/src/main/scala/raw/compiler/rql2/truffle/builtin/TruffleAwsPackage.scala
- raw-compiler-rql2-truffle/src/test/scala/raw/compiler/rql2/tests/extensions/TruffleExtensionsTest.scala
- raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/extensions/AwsPackageTest.scala
- raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/expressions/builtin/aws_package/AwsV4SignedRequestNode.java
- raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/expressions/builtin/location_package/LocationLsNode.java
- raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/runtime/list/BooleanList.java
- raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/runtime/list/ByteList.java
- raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/runtime/list/DoubleList.java
- raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/runtime/list/FloatList.java
- raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/runtime/list/IntList.java
- raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/runtime/list/ListLibrary.java
- raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/runtime/list/LongList.java
- raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/runtime/list/ObjectList.java
- raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/runtime/list/ShortList.java
- raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/runtime/list/StringList.java
- Implemented AWS Package
- Tests are not activated because XML package is not implemented yet.
> RD-9176 implement aws package in truffle

- raw-compiler-rql2/src/main/resources/META-INF/services/raw.compiler.rql2.EntryExtension
- raw-compiler-rql2/src/main/scala/raw/compiler/rql2/builtin/CsvPackage.scala
- raw-compiler-rql2/src/main/scala/raw/compiler/rql2/builtin/InMemoryLocationValueBuilder.scala
- raw-compiler-rql2/src/main/scala/raw/compiler/rql2/builtin/JsonPackage.scala
- raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/builtin/CsvPackageTest.scala
- Implemented Csv.InferAndRead
- Added encoding to Json.InferAndRead
> RD-9261 implement csv infer and read

- build.sbt
- project/Dependencies.scala
We are not using this lib anymore
> fix: remove unused sqlite dep

- .github/workflows/publish.yaml
> fix: /publish command output version in comment

- build.sbt
- project/Dependencies.scala
This dep was causing transitive vuln issue. See JIRA for more details.
This dep is not used anymore anyway
> RD-9312 transitive vuln netty-handler

- raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/output/JsonOutputTest.scala
I was too fast merging my other PR
> Json output test fix

- raw-compiler-rql2-truffle/src/main/scala/raw/compiler/rql2/truffle/builtin/TruffleFunctionPackage.scala
- raw-compiler-rql2-truffle/src/test/scala/raw/compiler/rql2/tests/builtin/TruffleBuiltInTest.scala
- raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/expressions/builtin/function_package/FunctionInvokeAfterNode.java
- Added Function.InvokeAfter entry
> RD-9460 implement function package in truffle for invoke after

- .github/workflows/scala-steward.yaml
- .scala-steward.conf
This will automatically create pull requests bumping outdated scala lib dependencies
> ci(gha): scala steward action

- raw-compiler-rql2-truffle/src/main/scala/raw/compiler/rql2/truffle/Rql2TruffleCompiler.scala
> RD-9478 Error running cloudwatch-iam-log-search.yml in truffle

- project/plugins.sbt
Integartes [sbt-java-formatter](https://github.com/sbt/sbt-java-formatter) to our plugins
> build(style): integrate sbt-java-formatter

- raw-compiler-rql2-truffle/src/test/scala/raw/compiler/rql2/tests/regressions/TruffleRegressionTest.scala
- raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/regressions/RD9554Test.scala
- raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/expressions/builtin/numeric/int_package/IntRangeNode.java
- raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/expressions/builtin/numeric/long_package/LongRangeNode.java
- raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/expressions/builtin/temporals/timestamp_package/TimestampRangeNode.java
- raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/runtime/iterable/sources/IntRangeCollection.java
- raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/runtime/iterable/sources/LongRangeCollection.java
- raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/runtime/iterable/sources/TimestampRangeCollection.java
Added the tests all failing without fixes. Then fixed it. I couldn't find a shorter fix.
> RD-9554: Fixed {Int/Long/Timestamp}.Range which couldn't be read multiple times

- .github/workflows/ci.yaml
- .gitignore
> more detailed ci steps

- .scala-steward.conf
- remove old rule for sbt update
- specify the new scala subprojects
> steward for language and extensions projects

- extensions/src/main/scala/raw/compiler/rql2/truffle/Rql2TruffleCompilerService.scala
- language/src/main/java/raw/runtime/truffle/ast/expressions/builtin/numeric/int_package/IntFromNode.java
- language/src/main/java/raw/runtime/truffle/ast/expressions/builtin/temporals/interval_package/IntervalParseNode.java
- language/src/main/java/raw/runtime/truffle/ast/io/csv/reader/parser/IterableParseCsvFile.java
- language/src/main/java/raw/runtime/truffle/ast/io/csv/reader/parser/IterableParseCsvString.java
- language/src/main/java/raw/runtime/truffle/ast/io/jdbc/JdbcQueryNode.java
- language/src/main/java/raw/runtime/truffle/ast/io/json/reader/JsonReadCollectionNode.java
- language/src/main/java/raw/runtime/truffle/ast/io/json/reader/parser/RecordParseJsonNode.java
- language/src/main/java/raw/runtime/truffle/ast/io/xml/parser/XmlParseCollectionNode.java
- language/src/main/java/raw/runtime/truffle/ast/io/xml/parser/XmlReadCollectionNode.java
- language/src/main/java/raw/runtime/truffle/runtime/generator/collection/compute_next/operations/EquiJoinComputeNext.java
- language/src/main/java/raw/runtime/truffle/runtime/generator/collection/compute_next/operations/JoinComputeNext.java
- language/src/main/java/raw/runtime/truffle/runtime/generator/collection/compute_next/sources/CsvReadComputeNext.java
- language/src/main/java/raw/runtime/truffle/runtime/generator/collection/compute_next/sources/CsvReadFromStringComputeNext.java
- language/src/main/java/raw/runtime/truffle/runtime/generator/collection/compute_next/sources/JdbcQueryComputeNext.java
- language/src/main/java/raw/runtime/truffle/runtime/generator/collection/compute_next/sources/JsonReadComputeNext.java
- language/src/main/java/raw/runtime/truffle/runtime/generator/collection/compute_next/sources/ReadLinesComputeNext.java
- language/src/main/java/raw/runtime/truffle/runtime/generator/collection/compute_next/sources/XmlParseComputeNext.java
- language/src/main/java/raw/runtime/truffle/runtime/generator/collection/compute_next/sources/XmlReadComputeNext.java
- language/src/main/java/raw/runtime/truffle/runtime/iterable/sources/CsvCollection.java
- language/src/main/java/raw/runtime/truffle/runtime/iterable/sources/CsvFromStringCollection.java
- language/src/main/java/raw/runtime/truffle/runtime/iterable/sources/JdbcQueryCollection.java
- language/src/main/java/raw/runtime/truffle/runtime/iterable/sources/JsonReadCollection.java
- language/src/main/java/raw/runtime/truffle/runtime/iterable/sources/XmlParseCollection.java
- language/src/main/java/raw/runtime/truffle/runtime/iterable/sources/XmlReadCollection.java
- language/src/main/java/raw/runtime/truffle/runtime/record/RecordObject.java
- Fixed parser direct call nodes
> RD-9634 fix all truffle too big errors part ii parsers direct calls

- snapi-client/src/test/scala/raw/compiler/rql2/tests/spec/PropagationTest.scala
- snapi-frontend/src/main/java/module-info.java
- snapi-frontend/src/main/resources/META-INF/services/raw.compiler.rql2.api.EntryExtension
- snapi-frontend/src/main/scala/raw/compiler/rql2/SemanticAnalyzer.scala
- snapi-frontend/src/main/scala/raw/compiler/rql2/builtin/TestPackage.scala
Added tests as `TestPackage`, that hit the bug. There are four failures without the patch.
> RD-10252: Fix desugaring when ValueParam are unexpectedly nullable/tryable

- .github/workflows/publish.yaml
- client/release.sh
- snapi-client/release.sh
- snapi-frontend/release.sh
- snapi-truffle/release.sh
- utils/release.sh
make sure each shell from sbt ci release steps are using the right JVM
> fix(ci)(publish):  make sure to use the right jvm

- README.md
- client/build.sh
- launcher/build.sh
- python-client/build.sh
- snapi-client/build.sh
- snapi-frontend/build.sh
- snapi-truffle/build.sh
- tests.sh
- utils/build.sh
If you don´t use the full version name and it is the first time you try to install java graalce from sdk man it might fail.
So we now use the full version
> fix(build): better sdk java install

- client/build.sh
- client/release.sh
- launcher/build.sh
- python-client/build.sh
- snapi-client/build.sh
- snapi-client/release.sh
- snapi-client/test.sh
- snapi-frontend/build.sh
- snapi-frontend/release.sh
- snapi-frontend/test.sh
- snapi-truffle/build.sh
- snapi-truffle/release.sh
- utils/build.sh
- utils/release.sh
we install a version and use another. now we make sure to use the exact same
> fix(build): more accurate sdk jvm use

- .github/workflows/ci.yaml
- .github/workflows/publish.yaml
- sql-client/release.sh
- sql-client/test.sh
CI/CD adaptations for the new `sql-client` component
> refactor(ci)(cd): adapt for sql-client

- snapi-truffle/src/main/java/raw/runtime/truffle/ast/expressions/iterable/collection/CollectionFirstNode.java
- snapi-truffle/src/main/java/raw/runtime/truffle/ast/expressions/iterable/collection/CollectionLastNode.java
- snapi-truffle/src/main/java/raw/runtime/truffle/ast/expressions/iterable/collection/CollectionMkStringNode.java
- snapi-truffle/src/main/java/raw/runtime/truffle/ast/expressions/iterable/list/ListFilterNode.java
- snapi-truffle/src/main/java/raw/runtime/truffle/ast/expressions/iterable/list/ListTransformNode.java
- snapi-truffle/src/main/java/raw/runtime/truffle/ast/io/csv/writer/CsvIterableWriterNode.java
- snapi-truffle/src/main/java/raw/runtime/truffle/runtime/kryo/KryoNodes.java
- snapi-truffle/src/main/java/raw/runtime/truffle/runtime/operators/OperatorNodes.java
- Fixed not initializing and not closing generators in some nodes
> RD-10466 Fix not initializing and not closing iterators

- sql-client/src/main/scala/raw/client/sql/NamedParametersPreparedStatement.scala
- sql-client/src/main/scala/raw/client/sql/SqlTypesUtils.scala
- sql-client/src/main/scala/raw/client/sql/writers/TypedResultSetCsvWriter.scala
- sql-client/src/main/scala/raw/client/sql/writers/TypedResultSetJsonWriter.scala
Also fixed a couple of issues regarding null values and CSV rendering null fields wrong.
> Fixed RD-10499: Unsupported jsonb

- utils/project/Dependencies.scala
> update(utils): bump logback-classic to 1.14.12

- snapi-client/src/test/scala/raw/compiler/rql2/tests/builtin/collection/CollectionPackageTest.scala
- snapi-client/src/test/scala/raw/compiler/rql2/tests/builtin/list/ListPackageTest.scala
- snapi-client/src/test/scala/raw/compiler/rql2/tests/spec/LetFunRecTest.scala
- snapi-truffle/src/main/java/raw/runtime/truffle/runtime/function/Closure.java
- snapi-truffle/src/main/java/raw/runtime/truffle/runtime/list/BooleanList.java
- snapi-truffle/src/main/java/raw/runtime/truffle/runtime/list/ByteList.java
- snapi-truffle/src/main/java/raw/runtime/truffle/runtime/list/DoubleList.java
- snapi-truffle/src/main/java/raw/runtime/truffle/runtime/list/FloatList.java
- snapi-truffle/src/main/java/raw/runtime/truffle/runtime/list/IntList.java
- snapi-truffle/src/main/java/raw/runtime/truffle/runtime/list/LongList.java
- snapi-truffle/src/main/java/raw/runtime/truffle/runtime/list/ObjectList.java
- snapi-truffle/src/main/java/raw/runtime/truffle/runtime/list/RawArrayList.java
- snapi-truffle/src/main/java/raw/runtime/truffle/runtime/list/ShortList.java
- snapi-truffle/src/main/java/raw/runtime/truffle/runtime/list/StringList.java
- fixed the recursion bug and list take semantics
> RD-10522 Truffle execution error in recursive function call

- snapi-truffle/src/main/java/raw/compiler/snapi/truffle/builtin/json_extension/JsonParser.java
- snapi-truffle/src/main/java/raw/compiler/snapi/truffle/builtin/json_extension/TruffleParseJsonEntry.java
- snapi-truffle/src/main/java/raw/compiler/snapi/truffle/builtin/json_extension/TrufflePrintJsonEntry.java
- snapi-truffle/src/main/java/raw/compiler/snapi/truffle/builtin/json_extension/TruffleReadJsonEntry.java
- snapi-truffle/src/main/java/raw/compiler/snapi/truffle/builtin/xml_extension/TruffleParseXmlEntry.java
- snapi-truffle/src/main/java/raw/compiler/snapi/truffle/builtin/xml_extension/TruffleReadXmlEntry.java
- snapi-truffle/src/main/java/raw/runtime/truffle/ast/io/csv/writer/CsvIterableWriterNode.java
- snapi-truffle/src/main/java/raw/runtime/truffle/ast/io/csv/writer/CsvListWriterNode.java
- snapi-truffle/src/main/java/raw/runtime/truffle/ast/io/json/reader/JsonParseNode.java
- snapi-truffle/src/main/java/raw/runtime/truffle/ast/io/json/reader/JsonPrintNode.java
- snapi-truffle/src/main/java/raw/runtime/truffle/ast/io/json/reader/JsonReadValueNode.java
- snapi-truffle/src/main/java/raw/runtime/truffle/ast/io/json/reader/parser/ListParseJsonNode.java
- snapi-truffle/src/main/java/raw/runtime/truffle/ast/io/json/writer/JsonWriterNode.java
- snapi-truffle/src/main/java/raw/runtime/truffle/ast/io/xml/parser/XmlParseValueNode.java
- snapi-truffle/src/main/java/raw/runtime/truffle/ast/io/xml/parser/XmlReadValueNode.java
- Converted RootNodes to callTargets where needed
> RD-9867 convert RootNodes to RootCallTarget in parsers

- snapi-frontend/src/main/scala/raw/creds/api/Credentials.scala
- snapi-frontend/src/main/scala/raw/creds/api/CredentialsService.scala
- snapi-frontend/src/main/scala/raw/creds/client/ClientCredentials.scala
- snapi-frontend/src/main/scala/raw/creds/client/ClientCredentialsService.scala
- snapi-frontend/src/main/scala/raw/creds/local/LocalCredentialsService.scala
- snapi-frontend/src/main/scala/raw/creds/protocol/ProtocolCredentials.scala
> Revert "adds external connector protocol"

- snapi-frontend/src/main/scala/raw/sources/jdbc/snowflake/SnowflakeClient.scala
This is the case why some snowflake tests fail in our other repo
> Quick fix snowflake client

- snapi-frontend/src/main/scala/raw/compiler/rql2/builtin/RegexPackage.scala
Fix wildcard and regex broken links in docs
> fix(docs): current broken links

- snapi-frontend/src/main/scala/raw/compiler/rql2/builtin/LocationPackage.scala
> fix(docs): wildcard broken links

- sql-client/src/main/scala/raw/client/sql/metadata/DotSearchWithOneItem.scala
- sql-client/src/main/scala/raw/client/sql/metadata/DotSearchWithTwoItems.scala
- sql-client/src/main/scala/raw/client/sql/metadata/WordSearchWithOneItem.scala
- sql-client/src/main/scala/raw/client/sql/metadata/WordSearchWithThreeItems.scala
- sql-client/src/main/scala/raw/client/sql/metadata/WordSearchWithTwoItems.scala
Added a where clause in the queries for the auto-complete filtering out information_schema and pg_catalog
> RD-10568 Sql auto-complete shows postgres internal tables

- client/build.sh
- client/release.sh
- deps/kiama/build.sh
- deps/others/build.sh
- launcher/build.sh
- python-client/build.sh
- snapi-client/build.sh
- snapi-client/release.sh
- snapi-client/test.sh
- snapi-frontend/build.sh
- snapi-frontend/release.sh
- snapi-frontend/test.sh
- snapi-parser/build.sh
- snapi-parser/release.sh
- snapi-truffle/build.sh
- snapi-truffle/release.sh
- sql-client/build.sh
- sql-client/release.sh
- sql-client/test.sh
- utils/build.sh
- utils/release.sh
Let's answer no if sdk man is asking to use a new jvm as default
> refactor(build): less aggressive jvm setup

- client/build.sbt
- python-client/build.sbt
- snapi-client/build.sbt
- snapi-frontend/build.sbt
- snapi-parser/build.sbt
- snapi-truffle/build.sbt
- sql-client/build.sbt
- utils/build.sbt
can be useful for debugging between snapi components and main repo components interactions
> refactor(build)(tests): publish tests sources

- snapi-truffle/src/main/java/raw/runtime/truffle/runtime/generator/collection/off_heap_generator/input_buffer/InputBufferNodes.java
> RD-10719 - EquiJoin Not working properly for large datasets

- snapi-client/src/test/scala/raw/compiler/rql2/tests/lsp/LspDefinitionTest.scala
- snapi-client/src/test/scala/raw/compiler/rql2/tests/lsp/LspDotAutoCompleteTest.scala
- snapi-client/src/test/scala/raw/compiler/rql2/tests/lsp/LspHoverTest.scala
- snapi-client/src/test/scala/raw/compiler/rql2/tests/lsp/LspRenameTest.scala
- snapi-client/src/test/scala/raw/compiler/rql2/tests/lsp/LspWordAutoCompleteTest.scala
- snapi-frontend/src/main/scala/raw/compiler/rql2/lsp/CompilerLspService.scala
> RD-10698 runner crash report scala match error

- .github/workflows/ci.yaml
- .github/workflows/publish.yaml
- .sdkmanrc
- parsers/build.sh
- parsers/publish.sh
- parsers/release.sh
We make sure sbt will launch with the right JVM in `code-checks` steps
We took advantage of this PR to align sdk use java version
> fix(ci): use the right JVM for sbt doc step

- jinja-sql-client/src/main/java/module-info.java
- jinja-sql-client/src/main/scala/raw/client/jinja/sql/JinjaSqlCompilerService.scala
- jinja-sql-client/src/main/scala/raw/client/jinja/sql/JinjaSqlCompilerServiceBuilder.scala
- jinja-sql-client/src/test/scala/PreprocessingTest.scala
`sbt jinjaSqlClient/headerCreate jinjaSqlClient/Test/headerCreate`
> headers for jinjaclient

- .github/workflows/ci.yaml
- .github/workflows/publish.yaml
> bump jvm version in CI

- .github/workflows/ci.yaml
- build.sbt
- ci/check
- ci/test
- project/GenParserPlugin.scala
- improve custom tasks using java and javac bins 
- run CI outside of container
> refactor(ci): get out of container

- .github/actions/get-antlr4/action.yaml
- .github/workflows/ci.yaml
We add a CI step to download the antl4 jar and re-use it if present
We wrapped this in a custom github action
> feat(ci): get-antl4 ci action

- project/Dependencies.scala
use our kiama with integrated automatic module name
> chore(update): bump kiama to 2.5.1-2

- project/Dependencies.scala
- snapi-compiler/src/test/scala/com/rawlabs/snapi/compiler/tests/SnapiTestContext.scala
- snapi-compiler/src/test/scala/com/rawlabs/snapi/compiler/tests/builtin/S3PackageTest.scala
- snapi-compiler/src/test/scala/com/rawlabs/snapi/compiler/tests/builtin/credentials/LocationPackageTest.scala
- snapi-compiler/src/test/scala/com/rawlabs/snapi/compiler/tests/builtin/credentials/S3PackageTest.scala
- snapi-compiler/src/test/scala/com/rawlabs/snapi/compiler/tests/regressions/credentials/RD5932Test.scala
- snapi-frontend/src/main/scala/com/rawlabs/snapi/frontend/snapi/extensions/LocationDescription.scala
- snapi-frontend/src/main/scala/com/rawlabs/snapi/frontend/snapi/extensions/builtin/S3Package.scala
- snapi-truffle/src/main/java/com/rawlabs/snapi/truffle/ast/expressions/builtin/location_package/LocationFromHttpNode.java
- snapi-truffle/src/main/java/com/rawlabs/snapi/truffle/ast/expressions/builtin/location_package/LocationFromS3Node.java
- snapi-truffle/src/main/java/com/rawlabs/snapi/truffle/emitter/builtin/s3_extension/TruffleS3BuildEntry.java
This reverts commit 34ddcf546138763cc696522ceb06b3936919c3f5.
> Revert "Fixed RD-12458: Add awsCredential parameter to S3.Build (#531)"
