raw-labs/snapi

raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/csv/writer/CsvIterableWriterNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/csv/writer/CsvListWriterNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/csv/writer/internal/BoolWriteCsvNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/csv/writer/internal/ByteWriteCsvNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/csv/writer/internal/DateWriteCsvNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/csv/writer/internal/DecimalWriteCsvNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/csv/writer/internal/DoubleWriteCsvNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/csv/writer/internal/FloatWriteCsvNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/csv/writer/internal/IntWriteCsvNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/csv/writer/internal/LongWriteCsvNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/csv/writer/internal/NullableWriteCsvNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/csv/writer/internal/RecordWriteCsvNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/csv/writer/internal/ShortWriteCsvNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/csv/writer/internal/StringWriteCsvNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/csv/writer/internal/TimeWriteCsvNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/csv/writer/internal/TimestampWriteCsvNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/csv/writer/internal/TryableWriteCsvNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/runtime/exceptions/csv/CsvWriterRawTruffleException.java
This changeset defines a specific `CsvWriterRawTruffleException` for CSV writing, to be in line with other writers. Before merging make sure all these writer exceptions follow the same scheme (see the PR comment).
=> add-on to RD-9167: Define a specific CSV writer exception

.github/workflows/ci.yaml
Previous trigger was for `CI.yaml` instead of the existing `ci.yaml`
=> fix(ci): fix filename for the ci workflow trigger

.github/workflows/ci.yaml
Make use of github secrets to make sure credentials are not leaking in worflow logs.
We use a github action taking the secrets and setting them as env variables, which are picked up by the various test contexts
=> chore(ci): use github secrets

build.sbt
We don't want to publish the `raw-cli` api code. We are going to publish a fat JAR in a near future, making use [buildSnapi](https://github.com/raw-labs/snapi/blob/831e9b0fbfd8bb4bb292755813bf7ca82bb42e74/build.sbt#L537C1-L556) task
=> chore: skip publish raw-cli

raw-compiler-rql2-truffle/src/main/scala/raw/compiler/rql2/truffle/builtin/TruffleCsvPackage.scala, raw-compiler-rql2-truffle/src/test/scala/raw/compiler/rql2/tests/output/TruffleOutputTest.scala, raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/CompilerTestContext.scala, raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/builtin/BinaryPackageTest.scala, raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/output/CsvOutputTest.scala, raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/output/JsonOutputTest.scala, raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/regressions/RD7974Test.scala, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/csv/writer/internal/BinaryWriteCsvNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/csv/writer/internal/DateWriteCsvNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/csv/writer/internal/TimeWriteCsvNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/csv/writer/internal/TimestampWriteCsvNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/json/writer/internal/TimeWriteJsonNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/json/writer/internal/TimestampWriteJsonNode.java
Both JSON and CSV are expected to support binary fields/columns, by turning them into their base64-encoded string.
I've edited existing tests to add a binary value to the output data and checked it's rendered as the base64-encoded string.
The CSV test has some more changes because it was using the wrong ScalaTest predicate.
=> RD-8998: Support for binary items in JSON and CSV

raw-compiler-rql2-truffle/src/test/scala/raw/compiler/rql2/tests/benchmark/TruffleBenchmarkTest.scala, raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/benchmark/StressTests.scala
Added stress test to test code cache behavior when running multiple queries. The test won't run by default.
=> RD-9223 truffle-execution-load-test

build.sbt, project/Dependencies.scala, raw-sources-http/src/main/scala/raw/sources/bytestream/http/oauth2clients/GoogleApiKeyOAuth2Client.scala
The current jjwt-jackson is causing transitive dep vuln. there is no new version since april 2022.
We decide here to use `jwt-core` from [github.com/jwt-scala](https://github.com/jwt-scala) instead.
=> RD-9182 migrate from jjwt-jackson to jwt-core

project/Dependencies.scala
The current version is causing a transitive vuln issue (check JIRA for more details)
=> RD-9188 upgrade jackson-dataformat-yaml

raw-compiler-rql2-truffle/src/main/scala/raw/compiler/rql2/truffle/Rql2TruffleCompiler.scala, raw-compiler-rql2-truffle/src/main/scala/raw/compiler/rql2/truffle/builtin/TruffleJsonPackage.scala, raw-compiler-rql2-truffle/src/test/scala/raw/compiler/rql2/tests/regressions/TruffleRegressionTest.scala, raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/regressions/RD9228Test.scala, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/expressions/function/InvokeNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/expressions/function/MethodRefNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/expressions/iterable/list/ListTakeNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/json/reader/TryableTopLevelWrapper.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/runtime/function/MethodRef.java
This is a working version, although not sure of all details. I see it works.
I added the following steps:
* register methods using the existing `recurseFunProto`.
* added a `MethodRefNode` node to implement `IdnExp` when it points to a method (instead of using `ReadLocalVariable` and the like, I think those would't work. That node embeds a ref to the top-level function to be called. It's very similar to a `ClosureNode` except that it doesn't embed a materialized frame.
* `InvokeNode`: handle both objects `Closure` and `MethodRef` using `isInstanceOf`. I thought of defining a specific `MethodInvoke` node but when generating an `InvokeNode`, one doesn't know which kind of object will be passed as a parameter (e.g. `List.Transform` can receive a method or a closure).
I enabled a bunch of …
=> RD-9224: support for top level methods

tests.sh
We were using some legacy script testing only some part of the projects.
Now we are back testting them all in this repo context
=> RD-9242 Missing tests run in snapi

.github/workflows/publish.yaml, .github/workflows/release.yaml
This PR implement the following
- RD-9292 create github release after a new tag is pushed
- RD-9190 notify main repo when a new version is published
- RD-9245 build and attach `raw-cli-assembly` jar to the release as an asset
=> RD-9292 + RD-9293 + RD-9245 automatic github release

project/Dependencies.scala
The current version is causing a transitive dep vuln issue (check JIRA for more details)
Thanks to @inkytonik responsivness on https://github.com/inkytonik/kiama/pull/33 and https://github.com/inkytonik/kiama/pull/34 we can now bump to `2.5.1`
=> fix: bump kiama dep to 2.5.1 (RD-9183 + RD-9185)

raw-compiler-rql2-truffle/src/main/scala/raw/compiler/rql2/truffle/builtin/TruffleAwsPackage.scala, raw-compiler-rql2-truffle/src/test/scala/raw/compiler/rql2/tests/extensions/TruffleExtensionsTest.scala, raw-compiler-rql2/src/main/scala/raw/compiler/rql2/builtin/AwsPackage.scala, raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/builtin/CsvPackageTest.scala, raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/extensions/AwsPackageTest.scala, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/expressions/binary/DivNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/expressions/builtin/aws_package/AwsV4SignedRequestNode.java
I enabled back the aws truffle tests. ignored for the moment the ones that use xml as it is not implemented in truffle.
One thing to discuss before merging how to generate in the CI the environment variables for the credentials 
```
"AWS_SESSION_TOKEN"
"AWS_ACCESS_KEY_ID"
"AWS_SECRET_ACCESS_KEY"
```
A script that I used to generate these (Pavlos gracefully gave it to me). Maybe it helps
```
#!/bin/bash
role_name=Developers
account_id=<your account id>
aws sso login
file=$(find ~/.aws/sso/cache/ -type f -printf "%t - %p\n" | sort -nr | tail -1 | awk '{print $7}')
access_token=$(cat  $file| jq -r .accessToken)
rc=$(aws sso get-role-credentials --account-id $account_id --role-name $role_name --region eu-west-1 --access-token $access_token | jq .)
export AWS_ACCESS_KEY_ID=$(echo $rc | jq -r …
```
=> RD-9240 Address temporary credentials in AWS library

raw-compiler-rql2-truffle/src/main/scala/raw/compiler/rql2/truffle/builtin/TruffleJsonPackage.scala, raw-compiler-rql2-truffle/src/test/scala/raw/compiler/rql2/tests/regressions/TruffleRegressionTest.scala, raw-compiler-rql2/src/test/scala/raw/compiler/rql2/Rql2OutputTestContext.scala, raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/output/JsonOutputTest.scala, raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/regressions/RD3084Test.scala, raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/regressions/RD5714Test.scala, raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/regressions/RD5914Test.scala, raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/regressions/RD9228Test.scala, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/RawLanguage.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/expressions/record/RecordAddFieldNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/expressions/record/RecordBuildNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/expressions/record/RecordConcatNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/expressions/record/RecordProjNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/io/csv/reader/parser/RecordParseCsvNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/io/json/reader/parser/RecordParseJsonNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/io/json/writer/internal/RecordWriteJsonNode.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/runtime/record/RecordObject.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/runtime/record/RecordStorageObject.java
The `RecordObject` class has changed:
* values are stored in a `DynamicObject` like they used by stored in, but keys are field _indexes_ instead of field names. That permits to use that class as a storage object without messing up with duplicated keys.
* keys are stored in a `String[]` (possibly duplicated),
* the API write keys takes a key name _and_ an index, that permits to enter duplicated keys.
* the interop API that returns keys (non-duplicated) implements the renaming before returning the list of keys,
The export to JSON is using that API to write a JSON file (since duplicated keys are discouraged by the JSON specs) while certain language nodes (like `Concat`) are using the real keys in order to maintain the proper key names.
The `RecordObject` used to extend `DynamicObject` and …
=> RD-9079: Records with duplicate fields names

raw-compiler-rql2-truffle/src/main/scala/raw/compiler/rql2/truffle/Rql2TruffleCompiler.scala, raw-compiler-rql2-truffle/src/main/scala/raw/compiler/rql2/truffle/builtin/TruffleJsonPackage.scala, raw-compiler-rql2-truffle/src/test/scala/raw/compiler/rql2/tests/regressions/TruffleRegressionTest.scala, raw-compiler-rql2-truffle/src/test/scala/raw/compiler/rql2/tests/spec/TruffleSpecTest.scala, raw-compiler-rql2/src/main/scala/raw/compiler/rql2/SemanticAnalyzer.scala, raw-compiler-rql2/src/main/scala/raw/compiler/rql2/builtin/BinaryPackage.scala, raw-compiler-rql2/src/main/scala/raw/compiler/rql2/builtin/CsvPackage.scala, raw-compiler-rql2/src/main/scala/raw/compiler/rql2/builtin/JsonPackage.scala, raw-compiler-rql2/src/main/scala/raw/compiler/rql2/builtin/StringPackage.scala, raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/regressions/RD9229Test.scala
This is the patch to make sure a query isn't run when its result should be exported to a format that doesn't support the data type (e.g. records with nested collections when exporting to CSV, but also functions, packages, when exporting to anything).
Related packages `JsonPackage`, `CsvPackage`, `BinaryPackage` and `StringPackage` are exposing an API that checks the target data type and returns true/false depending how it's supported. The `Rql2TruffleCompiler` calls these APIs before building the full tree. Once the tree is built, it's wrapped into the writing nodes. I removed some checks that were performed there since we're checking upfront.
I added a test suite to exercise the change, and some existing tests were enabled.
=> RD-9229: data type checks in data exports

raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/output/TextOutputTest.scala
That test is breaking against the Scala executor that reports a slightly different error message. Maybe we can be a little relaxed in the assertion to make both pass? (I tried that one in Scala and it passed.)
The scala failure has both 'unsupported type' and 'expected either common string or option(common string) but got common int'.
=> Fixed TextOutputTest assertion

raw-compiler-rql2-truffle/src/test/scala/raw/compiler/rql2/tests/regressions/TruffleRegressionTest.scala, raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/regressions/RD9445Test.scala, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/io/json/writer/JsonWriteNodes.java
Scala compiler uses just one format string with milliseconds .  So I made the same for truffle.
Quick question:
there was an specific if then else for the case of times/timestamps with milliseconds or not.
Do we prefer this?
Usually its better to have a fixed format but  the format string ` HH:mm:ss[.SSS]` would still parse both cases (with milliseconds and without).
If that is the case I can change the the scala compiler instead
=> RD-9445 Timestamp json output is different between truffle and scala

raw-compiler-rql2-truffle/src/main/resources/META-INF/services/raw.compiler.rql2.EntryExtension, raw-compiler-rql2-truffle/src/main/scala/raw/compiler/rql2/truffle/builtin/TruffleMySQLPackage.scala, raw-compiler-rql2-truffle/src/main/scala/raw/compiler/rql2/truffle/builtin/TruffleOraclePackage.scala, raw-compiler-rql2-truffle/src/main/scala/raw/compiler/rql2/truffle/builtin/TrufflePostgreSQLPackage.scala, raw-compiler-rql2-truffle/src/main/scala/raw/compiler/rql2/truffle/builtin/TruffleSQLServerPackage.scala, raw-compiler-rql2-truffle/src/main/scala/raw/compiler/rql2/truffle/builtin/TruffleSnowflakePackage.scala, raw-compiler-rql2/src/main/resources/META-INF/services/raw.compiler.rql2.EntryExtension, raw-compiler-rql2/src/main/scala/raw/compiler/rql2/builtin/MySQLPackage.scala, raw-compiler-rql2/src/main/scala/raw/compiler/rql2/builtin/OraclePackage.scala, raw-compiler-rql2/src/main/scala/raw/compiler/rql2/builtin/PostgreSQLPackage.scala, raw-compiler-rql2/src/main/scala/raw/compiler/rql2/builtin/SQLServerPackage.scala, raw-compiler-rql2/src/main/scala/raw/compiler/rql2/builtin/SnowflakePackage.scala, raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/builtin/MySQLPackageTest.scala, raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/builtin/PostgreSQLPackageTest.scala, raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/builtin/SnowflakePackageTest.scala, raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/builtin/SqlServerPackageTest.scala, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/io/jdbc/JdbcQuery.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/runtime/exceptions/rdbms/JdbcExceptionHandler.java, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/runtime/exceptions/rdbms/JdbcParserRawTruffleException.java
Databases `.Read` calls are here implemented as sugar for `.Query`. This patch also impacts the scala executor which I have tested locally. I'll create a release from this branch in order to test Scala in CI.
* existing unimplemented `TruffleRead` nodes have been deleted. Desugaring takes care of the extension now.
* tests were re-enabled.
There are more changes than one would expect. When enabling more tests, some expected failures were exercised and our error message wasn't matching the expected one. The reason being that we didn't distinguish "column errors", hit when trying to decode a certain column as a certain type, from "database errors", hit for example on a connection failure.
Therefore I add a new exception and make sure it's triggered from all the failing column parsers. As …
=> RD-9446: Sql.Read/InferAndRead implemented as sugar for .Query

raw-compiler-rql2/src/main/scala/raw/compiler/rql2/builtin/XmlPackage.scala, raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/builtin/XmlPackageTest.scala, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/runtime/exceptions/rdbms/JdbcParserRawTruffleException.java
The XML typechecker shouldn't accept complex types for attributes. We can cope with `list` and `collection` because those are parsed item by item, and that would lead to lists and collections of one item. Why not. Like for fields. But records no.
=> Fixed RD-5910: XML typechecker shouldn't accept complex types for attributes

.github/workflows/ci.yaml, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/runtime/exceptions/rdbms/JdbcParserRawTruffleException.java
We integrate a java fmt check and also makes sure we are not breaking the `sbt doc` task.
Since the java formatter can mess with java comments. Like introducing line break after an  `{@link`
=> ci: check java fmt + doc gen

.scala-steward.conf
Tells scala steward not to spam us with sbt upgrades since we might do it little by little
=> chore(scala-steward): give us time to upgrade sbt version

raw-compiler-rql2-truffle/src/main/scala/raw/compiler/rql2/truffle/builtin/TruffleNullableTryablePackage.scala, raw-compiler-rql2-truffle/src/test/resources/META-INF/services/raw.compiler.rql2.EntryExtension, raw-compiler-rql2-truffle/src/test/scala/raw/compiler/rql2/tests/builtin/TruffleTestPackage.scala, raw-compiler-rql2/src/main/scala/raw/compiler/rql2/Propagation.scala, raw-compiler-rql2/src/test/resources/META-INF/services/raw.compiler.rql2.EntryExtension, raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/builtin/TestPackage.scala, raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/spec/PropagationTest.scala, raw-runtime-rql2-truffle/src/main/java/raw/runtime/truffle/ast/expressions/tryable/TryableNullableFlatMapNode.java
While trying to trigger certain code paths in `TruffleNullableTryablePackage` with new test cases in `PropagationTest`, I hit an unrelated bug. Hence the new tests, the new `TestPackage` code and the fix in `Propagation`.
I noticed several of the `toTruffle` paths in the `FlatMap` node were having an extra `Closure`, as if we'd create a tree with:
```
\x -> f(x)
```
which is equivalent to `f` itself. Removing those is a safe fix and it improves performance.
I tried to get rid of all calls to `recurseLambda`. This led me to implement a new truffle `Node` that protects both the tryable _and_ the nullable sides of a value. It's used a lot since as soon as a user types a type, it's both tryable and nullable.
=> RD-9540: Create fewer inner closures

raw-compiler-rql2-truffle/src/test/scala/raw/compiler/rql2/tests/regressions/TruffleRegressionTest.scala, raw-compiler-rql2/src/main/scala/raw/compiler/rql2/lsp/LspSyntaxAnalyzer.scala, raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/regressions/RD9409Test.scala
The regular inflexible parser is OK with that comma. We should instead accept it in the flexible parser.
=> RD-9409: Fix the flexible parser (LSP) to accept an extra comma before the `in`

raw-compiler-rql2/src/main/scala/raw/compiler/rql2/builtin/MySQLPackage.scala, raw-compiler-rql2/src/main/scala/raw/compiler/rql2/builtin/OraclePackage.scala, raw-compiler-rql2/src/main/scala/raw/compiler/rql2/builtin/PostgreSQLPackage.scala, raw-compiler-rql2/src/main/scala/raw/compiler/rql2/builtin/SQLServerPackage.scala, raw-compiler-rql2/src/main/scala/raw/compiler/rql2/builtin/SnowflakePackage.scala
There is a copy paste mistake for the databases `Read` documentation.
They have the same explanations as the `InferAndRead` entry.
=> Fixing documentation of rdbms

raw-compiler-rql2/src/main/scala/raw/compiler/rql2/errors/ErrorsPrettyPrinter.scala, raw-compiler-rql2/src/test/scala/raw/compiler/rql2/tests/builtin/collection/CollectionOrderByTest.scala
Added a test to trigger the bug and the fix.
I also walked through all errors and ensured they're referenced in `ErrorsPrettyPrinter`.
=> RD-9598: Missing error case in Errors.PrettyPrinter

.github/workflows/publish.yaml, .gitignore, extensions/project/Dependencies.scala, language/build.sbt, language/build.sh
- adds sbt task in order to output the dynver of language in version file
- extension is now reading from version file
- publish worfklow adapted to publish language package
:warning: publish workflow from pr will not work until merge to main branch. publish workflow is triggered from a repository_dispatch event, in github when a workflow is triggered from dispatch_event the workflow file is taken from the default_branch = main in our case
=> graal 21 publish and dynver

language/src/main/scala/raw/utils/package.scala
The original filter wouldn't catch files coming from sonatype.
=> Fix Jar files filtering in getResources

.github/workflows/publish.yaml, .github/workflows/release.yaml, .gitignore, publishcomment.sh, rebuild.sh
- we adpat `.github/workflows/publish.yaml` workflow to work with new components structure
- we disable `launcher` jar attachment in `.github/workflows/release.yaml` workflow until further notice
=> adapt publish workflow

snapi-frontend/src/main/scala/raw/compiler/base/TreeWithPositions.scala, snapi-frontend/src/main/scala/raw/inferrer/api/DateTimeFormatFinder.scala, snapi-frontend/src/main/scala/raw/inferrer/local/TextTypeInferrer.scala
Declared all the formatters in an object. When profiling, those were dominating the memory. That fix permitted to run 78K semantic analysis without hitting OutOfMemory.
This would lead to a leak only if we never free Inferrers. Maybe this is the case?
=> Relax memory pressure when allocating inferrers

snapi-frontend/src/main/java/module-info.java, snapi-frontend/src/test/scala/raw/creds/api/CredentialsTestContext.scala, snapi-truffle/src/main/java/raw/runtime/truffle/ast/io/jdbc/JdbcQuery.java, snapi-truffle/src/main/resources/reference.conf
When running `PostgreSQLPackageTruffleTest`, that line appears in the logs when using a `PostgreSQL` database. Same with other backends.
```
Using raw.runtime.rdbms.fetch-size: 100000 (int)
```
Some tests processing errors using the `Exception` out of the JDBC call, failed because of missing module declarations.
```
Actual: java.lang.IllegalAccessError: class raw.sources.jdbc.pgsql.PostgresqlClient (in module raw.snapi.frontend) cannot access class org.postgresql.util.PSQLException (in unnamed module @0x479d31f3) because module raw.snapi.frontend does not read unnamed module @0x479d31f3
```
=> RD-10206: Setting RDBMS fetch size from config

snapi-client/src/test/scala/raw/compiler/rql2/tests/builtin/StringPackageTest.scala, snapi-client/src/test/scala/raw/compiler/rql2/tests/builtin/credentials/OraclePackageTest.scala
This latest version passed: https://github.com/raw-labs/raw/pull/5179
I dropped the `.localdomain` so that the host was found (`localhost`) and the failure became the originally expected one.
=> Fix flaky tests

snapi-frontend/src/main/scala/raw/inferrer/local/TextTypeInferrer.scala, snapi-frontend/src/test/scala/raw/inferrer/local/RD10260.scala
Basically there was a match missing for anything else than primitives in the  TextTypeInferrer.GetType function.
=> Inferrer crashes with MatchError on an json with or-types

snapi-client/src/test/scala/raw/compiler/rql2/tests/lsp/LspCommentsFormatTest.scala, snapi-client/src/test/scala/raw/compiler/rql2/tests/spec/ConstTest.scala, utils/build.sbt, utils/project/Dependencies.scala, utils/src/main/java/module-info.java, utils/src/main/scala/raw/utils/RawUtils.scala
Note that this patch is _adding_ a dependency to `org.apache.commons.text` that has a utility performing the string escapes we need. Our `RawUtils.escape`/`descape` do not support dealing with UTF-8 escapes.
=> RD-10265: UTF-8 character escape failing

.github/workflows/ci.yaml, client/project/Dependencies.scala, snapi-client/test.sh, snapi-frontend/test.sh, tests.sh
This PR is optimizing the CI runs.
We first build.
Then we start in parallel code checks and tests
Each of thos are also running parallel actions
(snapi-client tests are running meanwhile snapi-frontend tests are running somewhere else)
( each code checks for each component are running in parallel as well)
we use action artifacts in order to build once and then forward the local ivy cache with the produced artifacts
We might save 5  to 7 min on each run with those optimizations
=> ci: build once, check and test in parallel

snapi-client/src/main/scala/raw/client/rql2/truffle/Rql2TruffleCompilerService.scala, snapi-client/src/test/scala/raw/compiler/rql2/tests/builtin/IntPackageTest.scala, snapi-truffle/src/main/java/raw/runtime/truffle/RawLanguage.java, snapi-truffle/src/main/java/raw/runtime/truffle/runtime/exceptions/RawTruffleInternalErrorException.java, snapi-truffle/src/main/java/raw/runtime/truffle/runtime/exceptions/RawTruffleRuntimeException.java, snapi-truffle/src/main/java/raw/runtime/truffle/tryable_nullable/Tryable.java
If hitting an internal error, the exception is caught and mistaken for a user-level one. The discrimination on `.isGuestException` isn't enough.
Our language can throw:
* `RawTruffleRuntimeException` and `RawTruffleValidationException` that have a user-visible message and can be reported as an execution or validation error to the user,
* `RawTruffleInternalErrorException` which is showing an internal error,
* any other regular exception that it triggers by calling libraries: `NoSuchElementException`, `NullPointerException`, etc.
All these exceptions end up wrapped as `PolyglotException`. I noticed method `.isInternalError` returns `true` for regular Java exceptions and `false` for `RawTruffleRuntimeException` and `RawTruffleValidationException`. By checking `.isInternalError`, we get the …
=> RD-10218: Don't report internal errors (exceptions due to internal errors) as a user-visible error

deps/others/build.sbt, snapi-frontend/project/Dependencies.scala, snapi-frontend/src/main/java/module-info.java, snapi-frontend/src/main/scala/raw/sources/jdbc/mysql/MySqlClient.scala
This version requires the patch that renames modules. Without explicitly naming the module, I couldn't get it found at startup.
Without adding the module dependency, running a query leads to:
```
java.lang.IllegalAccessError: class raw.sources.jdbc.mysql.MySqlClient (in module raw.snapi.frontend)
cannot access class com.mysql.cj.exceptions.CJCommunicationsException (in unnamed module @0xb4a355b)
because module raw.snapi.frontend does not read unnamed module @0xb4a355b
```
With the patch, the query returns the expected results.
=> RD-10256: Add the MySQL JDBC module to snapi-frontend

.github/workflows/sync-deps.yaml, deps/others/.gitignore, deps/others/build.sbt
This PR introduces a specific task in order to automate s3 sync for our custom dependencies.
This script is then used by the pipeline responsible to keep our deps synced
=> feat(deps)(automation): dynamic sync deps

snapi-parser/build.sbt
When publishing a release version we do `publishSigned`  so this sbt task needs to follow the same flow  as `publish`  and `publishLocal`
=> fix(snapi-parser)(build): misc

snapi-truffle/build.sbt, snapi-truffle/build.sh
We make sure to run `runJavaAnnotationProcessor` task before compiling/publishing
=> fix(snapi-truffle)(cd): publish tasks shoudl depend on runJavaAnnotationProcessor

client/src/main/scala/raw/client/writers/PolyglotCsvWriter.scala, client/src/main/scala/raw/client/writers/TypedPolyglotCsvWriter.scala, snapi-client/src/main/scala/raw/client/rql2/truffle/Rql2CsvWriter.scala, snapi-client/src/test/scala/raw/compiler/rql2/tests/output/CsvOutputTest.scala
I added tests that broke before the fixes.
That's because writers are writing items as if they were in an array. If switching to "object", tests pass.
=> RD-10503: CSV Truffle writers aren't writing null values correctly

snapi-client/src/test/scala/raw/compiler/rql2/tests/builtin/credentials/MySQLPackageTest.scala, snapi-frontend/src/main/scala/raw/sources/jdbc/api/JdbcClient.scala, snapi-frontend/src/main/scala/raw/sources/jdbc/api/JdbcTableLocation.scala, snapi-frontend/src/main/scala/raw/sources/jdbc/mysql/MySqlClient.scala, snapi-frontend/src/main/scala/raw/sources/jdbc/mysql/MySqlLocationBuilder.scala, snapi-frontend/src/main/scala/raw/sources/jdbc/mysql/MySqlSchemaLocationBuilder.scala, snapi-frontend/src/main/scala/raw/sources/jdbc/mysql/MySqlTableLocationBuilder.scala, snapi-frontend/src/main/scala/raw/sources/jdbc/pgsql/PostgresqlClient.scala, snapi-frontend/src/main/scala/raw/sources/jdbc/pgsql/PostgresqlLocationBuilder.scala, snapi-frontend/src/main/scala/raw/sources/jdbc/pgsql/PostgresqlSchemaLocationBuilder.scala, snapi-frontend/src/main/scala/raw/sources/jdbc/pgsql/PostgresqlTableLocationBuilder.scala, snapi-frontend/src/main/scala/raw/sources/jdbc/snowflake/SnowflakeClient.scala, snapi-frontend/src/main/scala/raw/sources/jdbc/snowflake/SnowflakeLocationBuilder.scala, snapi-frontend/src/main/scala/raw/sources/jdbc/snowflake/SnowflakeSchemaLocationBuilder.scala, snapi-frontend/src/main/scala/raw/sources/jdbc/snowflake/SnowflakeTableLocationBuilder.scala, snapi-frontend/src/main/scala/raw/sources/jdbc/sqlite/SqliteClient.scala, snapi-frontend/src/main/scala/raw/sources/jdbc/sqlserver/SqlServerClient.scala, snapi-frontend/src/main/scala/raw/sources/jdbc/sqlserver/SqlServerLocationBuilder.scala, snapi-frontend/src/main/scala/raw/sources/jdbc/sqlserver/SqlServerSchemaLocationBuilder.scala, snapi-frontend/src/main/scala/raw/sources/jdbc/sqlserver/SqlServerTableLocationBuilder.scala, snapi-frontend/src/test/scala/raw/inferrer/local/RD10439.scala
The problem was not using the database when asking the metadata for tables.
I had also to change the RDBMS clients as we were using a lot of times the credential name instead of the database base name.
So added a val `database: Option[String]` to the base jdbc client and changed the way of inferring.
=> RD-10439 data duplication on MySQL.InferAndRead

sql-client/src/main/scala/raw/client/sql/NamedParametersPreparedStatement.scala, sql-client/src/test/scala/raw/client/sql/TestSqlCompilerServiceAirports.scala
The code didn't check if the status was 'unknown' (in which case, we should make it nullable).
A test was added that reports a column has unknown nullability.
An existing test had to be fixed since we were asserting its output had a certain nullability. Since we changed the code, the nullability of its column changed.
Also, an existing test was still assuming decimals were surrounded with double quotes (which was the case before RD-10527 got fixed).
=> RD-10538: Nullable columns sometimes reported as non-nullable

sql-client/src/main/java/module-info.java
If not patched, the runner fails to load. I tested it locally.
=> Fix SQL module breakage

snapi-frontend/src/main/scala/raw/compiler/rql2/builtin/CsvPackage.scala, snapi-frontend/src/main/scala/raw/compiler/rql2/source/SourcePrettyPrinter.scala, snapi-frontend/src/test/scala/raw/compiler/rql2/Antlr4TypeTests.scala
* RD-10594: function parameter names aren't quote when needed
* RD-10593: `CsvPackage.outputWriteSupport` is crashing if passed a random type that isn't a collection or a list.
=> Fixed RD-10593 and RD-10594

deps/kiama/build.sbt, deps/others/build.sbt
- Stop try to locate only coursier cache, just use the `update.value` infos
- allow to re-publish locally kiama
=> refactor(deps)(others)(build): improve jar path retrieval

sql-client/src/main/resources/reference.conf, sql-client/src/main/scala/raw/client/sql/ErrorHandling.scala, sql-client/src/main/scala/raw/client/sql/NamedParametersPreparedStatement.scala, sql-client/src/main/scala/raw/client/sql/SqlCompilerService.scala, sql-client/src/test/scala/raw/client/sql/TestSqlCompilerServiceAirports.scala
Since schemas and tables appear only when adding credentials, this would invite users to add credentials when such error occurs.
=> RD-10542: Suggest adding credentials when a relation isn't found

sql-client/src/main/scala/raw/client/sql/NamedParametersPreparedStatement.scala, sql-client/src/main/scala/raw/client/sql/SqlIntervals.scala, sql-client/src/main/scala/raw/client/sql/SqlTypesUtils.scala, sql-client/src/main/scala/raw/client/sql/writers/TypedResultSetJsonWriter.scala, sql-client/src/test/scala/raw/client/sql/TestParseIntervals.scala, sql-client/src/test/scala/raw/client/sql/TestPrintIntervals.scala
In this PR:
* Added a way of checking if jdbc.OTHER is an interval or an json
* Added a validation for input parameters.
* Added an object SqlIntervals with functions to parse pgsql intervals and convert intervals to string.
=> RD-10539 SELECT :v ::interval AS column fails with internal error

snapi-truffle/src/main/java/raw/runtime/truffle/runtime/generator/collection/GeneratorNodes.java, snapi-truffle/src/main/java/raw/runtime/truffle/runtime/generator/collection/off_heap_generator/off_heap/order_by/OffHeapGroupByKeys.java, snapi-truffle/src/main/java/raw/runtime/truffle/runtime/kryo/KryoNodes.java, snapi-truffle/src/main/java/raw/runtime/truffle/runtime/operators/OperatorNodes.java
- Keycompare was broken after migrating to nodes from libraries
- Node sharing caused an issue in kryo (skipped some specializations)
We weren't aware of these bugs because kryo memory properties weren't applied to truffle before this PR
=> Support multiple engines bug fix

client/src/main/scala/raw/client/api/ProgramDescription.scala, snapi-client/src/main/scala/raw/client/rql2/truffle/Rql2TruffleCompilerService.scala, sql-client/src/main/scala/raw/client/sql/SqlCompilerService.scala, sql-client/src/test/scala/raw/client/sql/TestNamedParametersStatement.scala, sql-client/src/test/scala/raw/client/sql/TestSqlCompilerServiceAirports.scala
See the JIRA and its related subtasks for all details.
That one is only a fraction of the fix. It permits to describe an SQL program as:
* no declarations in the `decls` `Map` (it has no user declared functions),
* a defined `maybeRunnable` declaration as value. With parameters (potentially an empty list if none).
and a Snapi program as:
* its usual list of declarations, the top-level functions,
* if it has a final value, a defined `maybeRunnable` declaration: parameter-less since Snapi doesn't support to evaluate a program as a function.
* if it has no final value, an undefined `maybeRunnable`.
The rest of the patch are fixes to the SQL test codes that are testing the compiler API.
=> RD-10763: Replace maybeType by a Decl in ProgramDescription

snapi-parser/src/main/java/raw/psql/grammar/PsqlLexer.g4, snapi-parser/src/main/java/raw/psql/grammar/PsqlParser.g4, sql-client/src/main/scala/raw/client/sql/antlr4/RawSqlVisitor.scala, sql-client/src/test/scala/raw/client/sql/TestSqlParser.scala
- Square brackets were missing in the implementation
- Multiline comment skip spaces had a typo (`c\n`)
- Fixed the issue with multiline comments where if a space were missing between comments comment end and the comment, the parser consumed the comment end as part of the comment e.g `/*18*/` consumed `18*` as a single word and the final `/` was an error
=> RD-10800 Validation errors in SQL comments

.github/workflows/publish.yaml, parsers/build.sh, rebuild.sh
With the current setup, the published `pom.xml` of `snapi-frontend` is relying on a `-SNAPSHOT` version.
This PR is fixing that
=> fix(parsers): release build should make sure snapi-frontend includes a release version

snapi-frontend/src/main/scala/raw/compiler/rql2/builtin/DatePackage.scala
The Date.SubtractInterval and Date.AddInterval return timestamps and not dates, so I updated the documentation.
Do we want to update the docs, like what is done here, or change the functions to return dates and not timestamps ?
=> RD-10768 Documentation wrong on Snapi Date.SubtractInterval

snapi-client/src/test/scala/raw/compiler/rql2/tests/regressions/RD9616Test.scala, snapi-client/src/test/scala/raw/compiler/rql2/tests/truffle/regressions/TruffleRegressionTest.scala, snapi-truffle/src/main/java/raw/runtime/truffle/ast/expressions/builtin/temporals/interval_package/IntervalNodes.java
Rounding is done last so that we don't round days. It was a mistake. Added a test that would fail without the patch (both computations would mistakenly return 30 days).
=> RD-9616: Fix the computation of Interval.ToMillis

snapi-client/src/test/scala/raw/compiler/rql2/tests/regressions/RD10801Test.scala, snapi-client/src/test/scala/raw/compiler/rql2/tests/regressions/RD5893Test.scala, snapi-client/src/test/scala/raw/compiler/rql2/tests/truffle/regressions/TruffleRegressionTest.scala, snapi-frontend/src/main/scala/raw/compiler/base/errors/Errors.scala, snapi-frontend/src/main/scala/raw/compiler/base/errors/ErrorsPrettyPrinter.scala, snapi-frontend/src/main/scala/raw/compiler/rql2/builtin/JsonPackage.scala, snapi-frontend/src/main/scala/raw/compiler/rql2/builtin/XmlPackage.scala
Here's a fix to the fact our Json parser/reader can't load data that has duplicated fields (since it reads fields out of order, it wouldn't know which one to pick). Records with duplicated fields are considered as not supported, like functions, package, etc.
There was some refactoring of the `validateJsonType` function so that it can apply to both user entered types (which we can underline in the error) or the inferred entered type.
With that patch, `UnsupportedType` supports _hint_ which permits to flag the duplicate field in the error message returned to the user.
I also edited XML which cannot parse records with duplicate fields (duplicate tags lead to a collection).
As part of the fix, I noticed `Json.Print` was failing if its parameter wouldn't be supported by our reader. Which turns …
=> Fixed RD-10801: do not parse/read Json data that has duplicated record fields

build.sbt, project/BuildSettings.scala
SInce release of SNAPSHOT version is using `publish` task, everything was ok regarding what is defined in `root` but non-SNAPSHOT version (for example: release tag version)  is using `publishSigned` we also need to exlude it for `root` project
We do the same with `publishLocal`
=> fix(publish): explicit skip for publishSigned and publishLocal

.github/workflows/ci.yaml, .sbtops, .sdkmanrc
`.sbtopts` got lost when migrating from multi-sbt build def to single sbt build def
=> fix(sbt): .sbtops missing at root level

sql-client/src/main/scala/raw/client/sql/antlr4/RawSqlVisitor.scala, sql-client/src/test/scala/raw/client/sql/TestSqlCompilerServiceAirports.scala
Without the patch, and given the "totally unparsable" code tested, ANTLR returns the default result. Which by default is a `null` ref. We crash on that reference when setting positions.
=> Fixed RD-10867: SQL compiler crashes if given snapi code

snapi-client/src/test/scala/raw/compiler/rql2/tests/builtin/HttpPackageTest.scala, snapi-frontend/src/main/scala/raw/compiler/rql2/builtin/HttpPackage.scala, snapi-truffle/src/main/java/raw/runtime/truffle/ast/expressions/builtin/location_package/LocationBuildNode.java
With that changeset, they're filtered out.
=> Fixed RD-10865: Http.Get crashing if passed null key/value in args or headers

.github/workflows/ci.yaml, project/BuildSettings.scala, project/CopyrightHeader.scala
We move the way we manage our header license to an auto plugin.
We still make use of the `sbt-header` plugin but we override some methods and settings in order to have the following behavior
- if a file already contains a copyright header we are not touching it and sbt headerCheck will pass
- if no header is found we add a copyright header at compilation with current year 
This PR is only about this auto plugin, after we merge this another PR will come to align all copyright headers and years
We take advantage of this PR to re-activate `sbt headerCheckAll` in CI
=> refactor(build): CopyrightHeader AutoPlugin

build.sbt, sql-client/src/main/java/module-info.java
I think this was missing from https://github.com/raw-labs/snapi/pull/414
=> fix(sql-client): sources dep and require

.github/workflows/ci.yaml
because of recent change on raw-scala-runner image, we have multiple graalvm versions, here we make sure to use the right one in each shell before running sbt tasks
=> fix(ci): run the right jvm when runner image contains multiple

snapi-frontend/src/main/scala/raw/compiler/rql2/builtin/HttpPackage.scala
Added the type for args and headers and added an example.
This is how the new docs look like:
=> RD-10863 Improve Snapi docs on Http regarding 'args'

sql-client/src/main/scala/raw/client/sql/antlr4/RawSqlVisitor.scala, sql-client/src/test/scala/raw/client/sql/TestSqlCompilerServiceAirports.scala, sql-parser/src/main/java/raw/psql/grammar/PsqlParser.g4
Added a test and verified it fails without the patch.
=> Fixed RD-10924: SQL @default parser in multiline does not accept more than one word

client/src/main/scala/raw/client/api/CompilerService.scala, sql-client/src/main/scala/raw/client/sql/NamedParametersPreparedStatement.scala
It would be nice to test the change using an expired credential. What I believe happens is: the "connection error" that occurs due to the expired credential, occurs _at runtime_ for us, when running the SQL query. In the actual code logic, any `PSQLException` is assumed to be an internal failure, since the user query has been validated successfully. However a runtime error can be due to connection failures to the datasource (the case in the ticket), or "second level validation errors":
* the original source table is gone or was renamed: if so, our Postgres engine validates a user query reading a table that eventually doesn't exist,
* the table exists, but isn't readable,
* the password was changed, etc.
In this changeset, all PSQL errors (which include errors due to the remote source …
=> RD-10895: Salesforce credential expired leads to an unexpected error 500

snapi-frontend/src/main/scala/raw/creds/local/LocalCredentialsService.scala, sql-client/src/main/scala/raw/client/sql/NamedParametersPreparedStatement.scala, sql-client/src/main/scala/raw/client/sql/SqlCompilerService.scala, sql-client/src/test/scala/raw/client/sql/TestNamedParametersStatement.scala, sql-client/src/test/scala/raw/client/sql/TestSqlCompilerServiceAirports.scala
This is implemented using a postgres _temporary table_ that is created/cleaned at startup of each query, and filled when scopes are provided. An example query that is then possible:
```sql
SELECT
CASE WHEN 'dev' IN (SELECT * FROM scopes) THEN trip_id END AS trip_id,
departure_date,
arrival_date
FROM example.trips
```
When `"dev"` is in the scopes:
```json
[
{
"trip_id": 0,
"departure_date": "2016-02-27",
"arrival_date": "2016-03-06"
},
{
"trip_id": 1,
"departure_date": "2016-04-10",
"arrival_date": "2016-04-17"
},
{
"trip_id": 2,
"departure_date": "2016-05-22",
"arrival_date": "2016-05-29"
},
{
"trip_id": 3,
"departure_date": "2023-01-01",
"arrival_date": "2023-01-01"
}
]
```
When it's not:
```json
[
{
"trip_id": null,
"departure_date": "2016-02-27",
"arrival_date": "2016-03-06"
},
{ …
```
=> Make key scopes visible to SQL

.github/workflows/publish.yaml, build.sbt, project/BuildSettings.scala
Since latest Sonatype infra migration, the current usage of `sbt-ci-release` plugin is not working anymore
We might still face this issue until https://github.com/sbt/sbt-ci-release/issues/294 is solved,
To cope with this we publish packages to Github Apache Maven
=> refactor(publish): publish to ghr

sql-client/src/main/scala/raw/client/sql/antlr4/RawSqlSyntaxAnalyzer.scala, sql-client/src/test/scala/raw/client/sql/TestSqlParser.scala
- Fixed by striping trail and removing the extra new line
=> RD-11232 sql compiler crash parser computes a wrong line col

sql-client/src/main/scala/raw/client/sql/NamedParametersPreparedStatement.scala, sql-client/src/test/scala/raw/client/sql/TestSqlCompilerServiceAirports.scala
What is to be discussed here is: how to report that error? Technically the whole source code is failed, because no executable is found (that is the current patch). But underlining the whole code as people peacefully type a comment at the top, isn't convenient. Also, even an empty file should trigger an error?
Or can we underline the _end_ (last character) saying the SELECT statement is missing.
Or can we not report anything as a failure, e.g. `GetProgramDescription` would contain no errors, but also no "final executable", and fail only upon running? (Just thinking of this now.)
=> RD-11080: SqlCompiler crashes when a query is made of 100% comments

snapi-frontend/src/main/scala/raw/compiler/rql2/antlr4/RawSnapiVisitor.scala, snapi-frontend/src/test/scala/raw/compiler/rql2/Antlr4LSPTests.scala
I believe the mistake is `ErrorExp` (the class) instead of `ErrorExp()`, an instance. `ErrorExp` cannot be cast to class `Exp` as if it was an instance. The crash occurs without the fix.
I noticed another place in the visitor where the fix should be made, but I couldn't come up with any snapi code that would hit it (one needs an `ErrorExp` in place of a function parameter default value).
=> RD-11199: ClassCastException between ErrorExp and Exp

client/src/main/scala/raw/client/api/RawTypes.scala, snapi-frontend/src/main/scala/raw/compiler/rql2/Rql2TypeUtils.scala
It's not a common type that will be visible to outside. Parameters aren't locations, and more importantly: locations aren't part of the output.
=> Drop RawLocationType

sql-client/src/main/scala/raw/client/sql/SqlCompilerService.scala, sql-client/src/main/scala/raw/client/sql/SqlConnectionPool.scala, sql-client/src/main/scala/raw/client/sql/metadata/UserMetadataCache.scala, sql-client/src/test/scala/raw/client/sql/TestSqlCompilerServiceAirports.scala, sql-client/src/test/scala/raw/client/sql/TestSqlConnectionFailures.scala
Before the pool was global, the code logic was that a connection failure to FDW would be an internal bug, FDW should always be available, and the connection pool should be provisioned to match the expected usage.
To review carefully if this behavior is what we want, and is implemented properly: To report connection failures to the user, we should isolate the connection failure `SQLException` (those are identified with code `08xxx`), and process these ones as errors that are normal to hit sometimes:
* for `execute`, `validate` and `getProgramDescription`, they are caught are the message is reported (as a `String` or `ErrorMessage` with positions when needed). The `validate` and `getProgramDescription` need positions, I've put positions spanning the full code.
* for `hover`, we probably …
=> RD-11521: report connection failures to the user

compiler/src/main/scala/com/rawlabs/compiler/CompilerServiceProvider.scala, compiler/src/main/scala/com/rawlabs/compiler/Errors.scala, protocol-compiler/src/main/protobuf/com/rawlabs/protocol/compiler/completions.proto, protocol-compiler/src/main/protobuf/com/rawlabs/protocol/compiler/docs.proto, protocol-compiler/src/main/protobuf/com/rawlabs/protocol/compiler/location_config.proto, protocol-compiler/src/main/protobuf/com/rawlabs/protocol/compiler/messages.proto, protocol-compiler/src/main/protobuf/com/rawlabs/protocol/compiler/program_environment.proto
- Protocol fixes
- Adding copyright
- Removing old jackson annotations
=> Minor fixes to compiler protocol

README.md
This PR fixes the Markdown links.
Also, took the liberty to change a phrase and make it a paragraph.
---
Before:
After:
Preview: https://github.com/steenzout/snapi/blob/steenzout-readme-20240823/README.md
---
👋🏻
=> docs: correct links and change phrase

snapi-compiler/src/test/scala/com/rawlabs/snapi/compiler/tests/regressions/RD10971Test.scala, snapi-compiler/src/test/scala/com/rawlabs/snapi/compiler/tests/regressions/RD14684Test.scala, snapi-compiler/src/test/scala/com/rawlabs/snapi/compiler/tests/regressions/RD14685Test.scala, snapi-truffle/src/main/java/com/rawlabs/snapi/truffle/ast/io/json/reader/JsonParserNodes.java, snapi-truffle/src/main/java/com/rawlabs/snapi/truffle/ast/io/json/reader/parser/ListParseJsonNode.java, snapi-truffle/src/main/java/com/rawlabs/snapi/truffle/ast/io/json/reader/parser/RecordParseJsonNode.java
The crash was hit because we use `token.toString` when the `token` can be `null`. Instead I used `String.valueOf(token)`.
Also added tests for bugs hit while debugging that.
=> Fixed RD-10971

.mergify.yml, .scala-steward.conf
We add scala-steward conf combined with mergify in order to auto-merge patch updates from `com.raw-labs` packages 
it will only have effect once
=> feat: scala-steward conf and mergify for com.raw-labs groupId

snapi-compiler/src/test/scala/com/rawlabs/snapi/compiler/tests/builtin/CsvPackageTest.scala, snapi-compiler/src/test/scala/com/rawlabs/snapi/compiler/tests/builtin/HttpPackageTest.scala, snapi-frontend/src/main/scala/com/rawlabs/snapi/frontend/snapi/extensions/LocationDescription.scala
The added `HttpPackageTest` tests passing args are passing. Because we pass the URL to a library which figures out. The most challenging one is where half of the args is passed in the URL, and the other half as a formal list of arguments, they're merged because the library sorts it out.
Hence I remove the "TODO" comment that was in the code since there's nothing to do (?)
Also added a CSV test making sure we correctly handle a mistakenly passed directory (in place of a file).
=> RD-12433: Test that assert Http URL parsing is correctly handling arguments

sql-compiler/src/main/scala/com/rawlabs/sql/compiler/antlr4/SqlVisitor.scala, sql-compiler/src/test/scala/com/rawlabs/sql/compiler/TestSqlCompilerServiceAirports.scala
What happens is specific to LSP and `hover`.
* LSP calls do not fail when the ANTL4 parser has detected failures because we like to perform completion and the like even with syntax errors.
* Hover has a specificity that if hovering an argument like `:iata`, we need to perform some code semantic analysis to compute the _type_ of the argument. This involves passing the query to postgres to let it do its own inference and checks (sometimes the type is totally inferred by postgres).
* When there are syntax errors, we'll get errors and postgres won't be able to infer, fine. But having two statements isn't always an error (they can be comments) so we just go and try, but _after cutting the code at the first statement_.
The bug we hit is that the parsed tree contains references to arguments like …
=> RD-14898: SqlCompiler crashes when running 'hover' against a query that has two statements

sql-compiler/src/main/scala/com/rawlabs/sql/compiler/SqlTypesUtils.scala, sql-compiler/src/main/scala/com/rawlabs/sql/compiler/writers/TypedResultSetJsonWriter.scala, sql-compiler/src/test/scala/com/rawlabs/sql/compiler/TestSqlCompilerServiceAirports.scala
Postgres queries can legitimately return arrays as columns. So far the SQL compiler service wouldn't support them. Here's a patch to support them. Added a test to exercise the logic and make sure it all goes to the output.
=> Fixed RD-15104: Support arrays in SQL output
